# Use an official Python runtime as a parent image
FROM python:3-slim

# Set the working directory to /app
WORKDIR /work

# Install Ansible and NAPALM packages
RUN pip install ansible ncclient napalm napalm-ansible

